services:
  - type: web
    name: smart-nail-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true

